apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-scubbo.fullname" . }}-admin-creds
  labels:
    {{- include "gitea-scubbo.labels" . | nindent 4 }}
stringData:
  # https://stackoverflow.com/a/64325744/1040915
  {{- if .Release.IsInstall }}
  username: {{ printf "admin-%s" (randAlphaNum 5) }}
  password: {{ randAlphaNum 20 }}
  {{- else }}
  username: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin-creds" (include "gitea-scubbo.fullname" .))).data "username" | b64dec }}
  password: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin-creds" (include "gitea-scubbo.fullname" .))).data "password" | b64dec }}
  {{ end }}
---
# This ClusterRole and Binding make it possible to access the above secret from another namespace - see https://stackoverflow.com/q/73796615/1040915
#
# This is necessary so that Drone CI can call the API to get/create an OAuth app for access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-for-secret-access
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-secret-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-for-secret-access
subjects:
  - kind: ServiceAccount
    name: service-account-for-secret-access
    namespace: drone
