apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-scubbo.fullname" . }}-init
  labels:
    {{- include "gitea-scubbo.labels" . | nindent 4 }}
type: Opaque
stringData:
  configure_gitea.sh: |-
    #!/usr/bin/env bash

    set -uo pipefail
    set -x

    echo '==== BEGIN GITEA CONFIGURATION ===='

    function configure_admin_user() {
      echo "Printing a lot of debugging"
      gitea admin user list --admin
      echo "Admin Username"
      echo $GITEA_ADMIN_USERNAME
      echo "Grepped admin list:"
      gitea admin user list --admin | grep "$GITEA_ADMIN_USERNAME"
      echo "Grepped awked admin list:"
      gitea admin user list --admin | grep -e "\s\+${GITEA_ADMIN_USERNAME}\s\+" | awk -F " " "{printf \$1}"
      local ACCOUNT_ID=$(gitea admin user list --admin | grep -e "\s\+${GITEA_ADMIN_USERNAME}\s\+" | awk -F " " "{printf \$1}")
      echo "DEBUG - accountId is:";
      echo $ACCOUNT_ID;
      if [[ -z "${ACCOUNT_ID}" ]]; then
        echo "No admin user '${GITEA_ADMIN_USERNAME}' found. Creating now..."
        gitea admin user create --admin --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}" --email "admin@example.org" --must-change-password=false
        echo '...created.'
      else
        echo "Admin account '${GITEA_ADMIN_USERNAME}' already exist. Running update to sync password..."
        gitea admin user change-password --username "${GITEA_ADMIN_USERNAME}" --password "${GITEA_ADMIN_PASSWORD}"
        echo '...password sync done.'
      fi
    }

    configure_admin_user