apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea-scubbo.fullname" . }}
  labels:
    {{- include "gitea-scubbo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "gitea-scubbo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea-scubbo.fullname" . }}-ssh
  labels:
    {{- include "gitea-scubbo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{.Values.service.sshPort}}
      targetPort: 22
      nodePort: {{ .Values.service.sshNodePort }}
      protocol: TCP
      name: ssh
  # NodePort so that connections directly to the Router via public DNS
  # can be forwarded to this service
  # (Cloudflare Tunnels cannot carry ssh connections)
  type: NodePort
  selector:
    {{- include "gitea-scubbo.selectorLabels" . | nindent 4 }}