apiVersion: v2
name: gitea-internal
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: gitea
    repository: https://dl.gitea.io/charts/
    version: "6.0.5"
