apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  # https://doc.traefik.io/traefik/providers/kubernetes-ingress/#ingressclass
  controller: traefik.io/ingress-controller