dataVolume:
  nfsServer: rassigma.avril
  nfsPath: /mnt/BERTHA/gitea

gitea:
  global:
    storageClass: freenas-iscsi-csi

  image:
    tag: "1.19.2"

  persistence:
    enabled: true
    create: false
    # existingClaim: gitea-data-pvc # old name
    claimName: gitea-data-pvc

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    className: traefik
    annotations:
      ingress.kubernetes.io/custom-request-headers: "Host: gitea.scubbo.org"
      # Without this, I was getting `413 Request Entity Too Large` errors
      # https://stackoverflow.com/questions/62657398/how-to-set-max-request-body-size-in-traefik-ingress-controller-for-kubernetes
      # originally put me on to it, though there's more documentation in
      # https://doc.traefik.io/traefik/middlewares/http/buffering/#memrequestbodybytes,
      # though that didn't actually show to set the value on the ingress itself.
      #
      # In the end I gave up and used Copilot :'(
      #
      # `maxrequestbodybytes` chosen by finding the size of the image I'm trying to upload (1.57GB) and adding 20% buffer
      # `memrequestbodybytes` chosen by keeping it in-proportion with `maxrequest` from example values (approx. 2x)
      traefik.ingress.kubernetes.io/max-request-body-bytes: "1884000000"
    hosts:
      - host: gitea.avril
        paths:
          - path: /
            pathType: Prefix

  gitea:
    metrics:
      enabled: true
    config:
      server:
        ROOT_URL: "https://gitea.scubbo.org"
        SSH_DOMAIN: ssh-gitea.scubbo.org
      packages:
        ENABLED: "true"

  postgresql:
    enabled: true
    image:
      tag: "16.6.0-debian-12-r2"
    primary:
      nodeAffinityPreset:
        type: hard
        key: kubernetes.io/arch
        values:
          # Bitnami doesn't support ARM64: https://github.com/bitnami/charts/issues/7305
          - amd64

  postgresql-ha:
    enabled: false

  redis-cluster:
    # As of Chart version 10.0.0, Gitea Helm chart maintainers recommend pinning images of dependencies
    # https://gitea.com/gitea/helm-chart#dependency-versioning
    image:
      tag: 7.2.3-debian-11-r1
