dataVolume:
  nfsServer: rassigma.avril
  nfsPath: /mnt/BERTHA/gitea

gitea:
  global:
    storageClass: longhorn

  persistence:
    enabled: true
    existingClaim: gitea-data-pvc

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    className: traefik
    annotations:
      ingress.kubernetes.io/custom-request-headers: "Host: gitea.scubbo.org"
    hosts:
      - host: gitea.avril
        paths:
          - path: /
            pathType: Prefix

  gitea:
    metrics:
      enabled: true
    config:
      server:
        ROOT_URL: "https://gitea.scubbo.org"
        SSH_DOMAIN: ssh-gitea.scubbo.org
      packages:
        ENABLED: "true"


  memcached:
    # Since Bitnami don't support ARM64/Raspberries Pi
    image:
      repository: "arm64v8/memcached"
      tag: "1.6.17"
    arguments: []
    diagnosticMode:
      enabled: false

  postgresql:
    enabled: true
    image:
      # Bitnami doesn't support ARM64: https://github.com/bitnami/charts/issues/7305
      repository: "arm64v8/postgres"
      tag: "15.1"

