apiVersion: v2
name: gitea
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.18.0"

dependencies:
  - name: gitea
    repository: https://dl.gitea.io/charts/
    version: "9.6.1"
