pod-gateway:
  settings:
    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 192.168.0.0/16"
#    VPN_BLOCK_OTHER_TRAFFIC: true
    VPN_INTERFACE: wg0
  addons:
    # https://github.com/k8s-at-home/library-charts/blob/2b4e0aa1ef5f8c6ef4ac14c2335fc9a008394ed6/charts/stable/common/templates/addons/vpn/openvpn/_container.tpl
    # https://github.com/k8s-at-home/library-charts/blob/2b4e0aa1ef5f8c6ef4ac14c2335fc9a008394ed6/charts/stable/common/values.yaml#L477
    vpn:
      enabled: true

      type: openvpn
      openvpn:
        authSecret: openvpn-creds
      configFileSecret: openvpn-config

#      type: wireguard
#      configFileSecret: wireguard-config