{{- range (index .Values "pod-gateway" "routed_namespaces") }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: limit-traffic-to-internal-only
  namespace: {{ . }}
spec:
  podSelector: {}
  ingress:
    - from:
        # Only allow ingress from K8S
        - ipBlock:
            cidr: 10.0.0.0/8
  egress:
    - to:
        # Only allow egress to K8S
        - ipBlock:
            cidr: 10.0.0.0/8
  policyTypes:
    - Ingress
    - Egress
{{- end }}