apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone-monitoring.fullname" . }}
  labels:
    {{- include "drone-monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.ports.webhook }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "drone-monitoring.selectorLabels" . | nindent 4 }}
