apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-for-dendrite-database
  namespace: dendrite
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: dendrite-nfs
