apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "prometheus.fullname" . }}-pv
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    {{- .Values.persistence.nfs | toYaml | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus.fullname" . }}-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "prometheus.fullname" . }}-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}