version: '3.8'

services:
  main:
    build:
      context: .
    secrets:
      - user_ssh_key
    volumes:
      - /mnt/BERTHA/pi-holeBackups:/host_system_dir
secrets:
  user_ssh_key:
    file: ~/.ssh/id_rsa

