apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-service-account
  namespace: blog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blog-service-account-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: blog-service-account
    namespace: blog
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
