# Taken from https://cogarius.medium.com/3-3-complete-guide-to-ci-cd-pipelines-with-drone-io-on-kubernetes-drone-metrics-with-prometheus-c2668e42b03f
# Refer to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint for explanation of fields
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator
    release: prometheus
  name: jellyfin-count
  namespace: prometheus
spec:
  namespaceSelector:
    matchNames:
      - jellyfin
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin-metrics
