apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: jellyfin-metrics
spec:
  type: LoadBalancer
  ports:
    - port: 8555
      targetPort: 8555
      name: metrics
      protocol: TCP
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: jellyfin-metrics