# Taken from https://cogarius.medium.com/3-3-complete-guide-to-ci-cd-pipelines-with-drone-io-on-kubernetes-drone-metrics-with-prometheus-c2668e42b03f
# Refer to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint for explanation of fields
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator
    # Note this is different from what is provided in the article - I guess the Prometheus stack's default labelling changes
    # between releases? There _has_ been a name change: see https://github.com/prometheus-community/community/issues/28#issuecomment-670406329
    #
    # Or, it might be the name of the release passed to `helm install`? Either way - this is what works for me!
    release: prometheus
  name: drone
  namespace: prometheus
spec:
  namespaceSelector:
    matchNames:
      - drone
  endpoints:
    - bearerTokenFile: /etc/prometheus/secrets/drone-metrics/token
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: drone
      app.kubernetes.io/name: drone-scubbo
