apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-config
  namespace: jellyfin
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteMany
  nfs:
    server: rassigma.avril
    path: "/mnt/BERTHA/etc/jellyfin/config"
  mountOptions:
    - nfsvers=4.2