apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-cache-pvc
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: jf-cache
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
