apiVersion: v1
kind: PersistentVolume
metadata:
  name: jf-cache
  namespace: jellyfin
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  nfs:
    server: rassigma.avril
    path: "/mnt/BERTHA/etc/jellyfin/cache"
  mountOptions:
    - nfsvers=4.2