apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-config-pvc
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: jf-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2G
