apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jf-media-pvc
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: jf-media
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3T
