---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-db
  namespace: grafana
spec:
  capacity:
    storage: 5M
  accessModes:
    - ReadWriteMany
  nfs:
    server: rassigma.avril
    path: "/mnt/BERTHA/etc/grafana/grafana-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-db-pvc
  namespace: grafana
spec:
  storageClassName: ""
  volumeName: grafana-db
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-config
  namespace: grafana
spec:
  capacity:
    storage: 100k
  accessModes:
    - ReadWriteMany
  nfs:
    server: rassigma.avril
    path: "/mnt/BERTHA/etc/grafana/grafana-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config-pvc
  namespace: grafana
spec:
  storageClassName: ""
  volumeName: grafana-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100k
