# Why not use the Kubernetes Runner?
# (https://docs.drone.io/runner/kubernetes/overview/)
# 1. I already have a working setup with Docker Runners and have no reason to want to migrate
# 2. "Kubernetes pipelines are considered experimental and may not be suitable for production use yet"
# 3. "Existing plugins may not be compatible with kubernetes pipelines and will need to be patched accordingly."
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "drone-scubbo.fullname" . }}
  labels:
    {{- include "drone-scubbo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "drone-scubbo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "drone-scubbo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: drone-runner
          image: drone/drone-runner-docker:1
          env:
            - name: DRONE_RPC_PROTO
              value: http
            - name: DRONE_RPC_HOST
              value: {{ include "drone-scubbo.fullname" . }}:{{ .Values.service.port}} # According to Kubernetes service DNS, this _should_ resolve without needing `.<namespace>.svc.cluster.local`
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.manualRPCSecretName | default "rpc-secret"}}
                  key: secret
            - name: DRONE_RUNNER_CAPACITY
              value: "2"
            - name: DRONE_RUNNER_NAME
              value: drone-runner
            - name: DRONE_RUNNER_VOLUMES
              value: "/var/run/docker.sock:/var/run/docker.sock"
          ports:
            - name: server-port
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock