---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "drone-scubbo.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.volume.nfsServer }}
    path: {{ .Values.volume.nfsPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drone-scubbo.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: {{ include "drone-scubbo.fullname" . }}-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
