apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoip
  namespace: plausible
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteMany
  nfs:
    server: rassigma.avril
    path: "/mnt/BERTHA/etc/plausible/geoip"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoip-pvc
  namespace: plausible
spec:
  storageClassName: ""
  volumeName: geoip
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1M
