global:
  storageClass: longhorn

dataVolume:
  nfsServer: rassigma.avril
  nfsPath: /mnt/BERTHA/gitea-internal

gitea:
  persistence:
    enabled: true
    existingClaim: gitea-internal-data-pvc

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    className: traefik
    hosts:
      - host: gitea-internal.avril
        paths:
          - path: /
            pathType: Prefix

  gitea:
    metrics:
      enabled: true
    config:
      server:
        ROOT_URL: "http://gitea-internal.avril"
        SSH_DOMAIN: ssh-gitea-internal.avril
      packages:
        ENABLED: "true"


  memcached:
    # Since Bitnami don't support ARM64/Raspberries Pi
    image:
      repository: "arm64v8/memcached"
      tag: "1.6.17"
    arguments: []
    diagnosticMode:
      enabled: false

  postgresql:
    enabled: true
    image:
      # Bitnami doesn't support ARM64: https://github.com/bitnami/charts/issues/7305
      repository: "arm64v8/postgres"
      tag: "15.1"

