apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ombi.fullname" . }}
  labels:
    {{- include "ombi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ombi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ombi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: ombi-config
        - name: sonarr
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12}}
          image: "lscr.io/linuxserver/sonarr:latest"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: sonarr-config
            - mountPath: /data
              name: ombi-data
        - name: radarr
      volumes:
        - name: ombi-config
          persistentVolumeClaim:
            claimName: {{ include "ombi.fullname" . }}-pvc
        - name: ombi-data
          persistentVolumeClaim:
            claimName: {{ include "ombi.fullname" . }}-data-pvc
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: {{ include "ombi.fullname" . }}-sonarr-config-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
