---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-data-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 5T
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.volume.dataNFSServer }}
    path: {{ .Values.volume.dataNFSPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-data-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5T
# TODO - templatize these similar definitions
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-ombi-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $.Values.volume.configNFSServer }}
    path: /mnt/BERTHA/etc/ombi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-ombi-config-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-ombi-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-sonarr-config-pv
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $.Values.volume.configNFSServer }}
    path: /mnt/BERTHA/etc/sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-sonarr-config-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-sonarr-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-radarr-config-pv
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $.Values.volume.configNFSServer }}
    path: /mnt/BERTHA/etc/radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-radarr-config-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-radarr-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-prowlarr-config-pv
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $.Values.volume.configNFSServer }}
    path: /mnt/BERTHA/etc/prowlarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-prowlarr-config-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-prowlarr-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-nzbget-config-pv
spec:
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $.Values.volume.configNFSServer }}
    path: /mnt/BERTHA/etc/nzbget
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-nzbget-config-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-nzbget-config-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ombi.fullname" . }}-usenet-downloads-pv
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $.Values.volume.dataNFSServer }}
    path: /mnt/NEW_BERTHA/ombi-data/usenet
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ombi.fullname" . }}-usenet-downloads-pvc
spec:
  storageClassName: ""
  volumeName: {{ include "ombi.fullname" . }}-usenet-downloads-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
